import datetime
import re

import dearpygui.dearpygui as dpg

from .fonts import HEADER, LABEL, MUTED, styled_text


class ImportMixin:
    """Parses pasted Discord / plain-text event text and loads it into the editor."""

    # ── Import dialog ─────────────────────────────────────────────────────

    def open_import_dialog(self):
        """Open a modal with a paste area and Import button."""
        win_tag = "import_dialog_win"
        if dpg.does_item_exist(win_tag):
            dpg.delete_item(win_tag)
        with dpg.window(tag=win_tag, label="Import Event", modal=True,
                        width=480, no_resize=False, no_scrollbar=True,
                        pos=dpg.get_mouse_pos(local=False)):
            styled_text("IMPORT EVENT", HEADER)
            styled_text(
                "Paste a Discord or plain-text formatted event below.\n"
                "Supports: titles, timestamps, genres, lineup slots, and Open Decks.",
                MUTED, wrap=450,
            )
            paste_tag   = f"{win_tag}_paste"
            dpg.add_input_text(tag=paste_tag, multiline=True, width=-11, height=120)
            status_text = styled_text("", LABEL, show=False)

            def _preview(s, a, _pi=paste_tag, _st=status_text):
                raw = (dpg.get_value(_pi) or "").strip()
                if not raw:
                    dpg.show_item(_st); dpg.set_value(_st, "Paste something first."); return
                parsed = self._parse_event_text(raw)
                if not parsed:
                    dpg.show_item(_st); dpg.set_value(_st, "Could not recognise any event data."); return
                n_slots = len(parsed.get("slots", []))
                title = parsed.get("title") or "Untitled"
                genres = ", ".join(parsed.get("genres", [])) or "\u2014"
                dpg.show_item(_st)
                dpg.set_value(_st, f'"{title}" \u2014 {n_slots} slot(s) \u2014 Genres: {genres}')

            def _import(s, a, _pi=paste_tag, _st=status_text, _wt=win_tag):
                raw = (dpg.get_value(_pi) or "").strip()
                if not raw:
                    dpg.show_item(_st); dpg.set_value(_st, "Paste something first."); return
                parsed = self._parse_event_text(raw)
                if not parsed:
                    dpg.show_item(_st); dpg.set_value(_st, "Could not recognise any event data."); return
                self._apply_parsed_event(parsed)
                dpg.delete_item(_wt)

            with dpg.group(horizontal=True):
                dpg.add_button(label="Preview", width=140, callback=_preview)
                import_btn = dpg.add_button(label="Import", width=140, callback=_import)
                dpg.bind_item_theme(import_btn, "primary_btn_theme")



    # ── Parser ────────────────────────────────────────────────────────────

    def _parse_event_text(self, text: str) -> dict | None:
        """Parse text generated by OutputGenerator back into event data.

        Detects format automatically (Discord vs plain-text) and delegates to
        the appropriate sub-parser.  Both parsers recover:
          • title + volume number
          • event timestamp
          • genre list
          • per-slot name, genre, and duration (computed from time deltas)
        """
        lines = [ln.strip() for ln in text.strip().splitlines() if ln.strip()]
        if not lines:
            return None
        is_discord = any(re.search(r'<t:\d+:', ln) for ln in lines)
        return self._parse_discord(lines) if is_discord else self._parse_plain(lines)

    # ── Discord format ────────────────────────────────────────────────────

    def _parse_discord(self, lines: list[str]) -> dict | None:
        """Parse the Discord output format:

            # Event Title VOL.3
            # <t:UNIX:F> (<t:UNIX:R>)
            ## Genre1 // Genre2
            ### LINEUP
            <t:UNIX:t> | **DJ Name** (Genre)
        """
        parsed = {"title": "", "vol": "", "timestamp": "", "genres": [], "slots": [], "names_only": False}
        slot_times: list[int] = []
        in_lineup = False

        for line in lines:
            # ── Event timestamp: "# <t:UNIX:F> (<t:UNIX:R>)" ────────────
            m = re.search(r'<t:(\d+):F>', line)
            if m and not parsed["timestamp"]:
                dt = datetime.datetime.fromtimestamp(int(m.group(1)))
                parsed["timestamp"] = dt.strftime("%Y-%m-%d %H:%M")
                continue

            # ── Slot with timestamp: "<t:UNIX:t> | **Name** (Genre)" ─────
            m = re.match(r'^<t:(\d+):t>\s*\|\s*(.+)$', line)
            if m:
                unix = int(m.group(1))
                rest = re.sub(r'\*\*(.+?)\*\*', r'\1', m.group(2)).strip()
                name, genre = self._extract_name_genre(rest)
                slot_times.append(unix)
                parsed["slots"].append({"name": name, "genre": genre, "duration": "60"})
                continue

            # ── Section header: "### LINEUP" ─────────────────────────────
            if re.match(r'^#{0,3}\s*LINEUP\s*$', line, re.IGNORECASE):
                in_lineup = True
                continue

            # ── Genre line: "## Genre1 // Genre2" ────────────────────────
            if '//' in line and not in_lineup:
                genre_text = re.sub(r'^#+\s*', '', line).strip()
                parsed["genres"] = [g.strip() for g in genre_text.split("//") if g.strip()]
                continue

            # ── Title: "# Night Beats VOL.3" (no timestamp on this line) ─
            m = re.match(r'^#+\s+(.+)$', line)
            if m and not parsed["title"] and '<t:' not in line:
                self._split_title_vol(m.group(1).strip(), parsed)
                continue

            # ── Names-only slot: plain text line inside LINEUP section ────
            if in_lineup and not re.match(r'^#+', line):
                parsed["names_only"] = True
                parsed["slots"].append({"name": line, "genre": "", "duration": "60"})

        self._compute_slot_durations(parsed["slots"], slot_times)
        return parsed if (parsed["title"] or parsed["slots"]) else None

    # ── Plain-text / local format ─────────────────────────────────────────

    def _parse_plain(self, lines: list[str]) -> dict | None:
        """Parse the local/plain-text output format:

            Event Title VOL.3
            2025-06-01 @ 20:00 (PST)
            Genre1 // Genre2
            LINEUP
            20:00 | DJ Name (Genre)
        """
        parsed = {"title": "", "vol": "", "timestamp": "", "genres": [], "slots": [], "names_only": False}
        slot_times: list[int] = []
        in_lineup = False

        for line in lines:
            # ── Timestamp: "YYYY-MM-DD @ HH:MM (TZ)" ─────────────────────
            m = re.match(r'^(\d{4}-\d{2}-\d{2})\s*@\s*(\d{1,2}:\d{2})', line)
            if m and not parsed["timestamp"]:
                parsed["timestamp"] = f"{m.group(1)} {m.group(2).zfill(5)}"
                continue

            # ── Section header: "LINEUP" ──────────────────────────────────
            if re.match(r'^LINEUP\s*$', line, re.IGNORECASE):
                in_lineup = True
                continue

            if in_lineup:
                # ── Timed slot: "HH:MM | DJ Name (Genre)" ────────────────
                m = re.match(r'^(\d{1,2}:\d{2})\s*\|\s*(.+)$', line)
                if m:
                    time_str = m.group(1)
                    name, genre = self._extract_name_genre(m.group(2).strip())
                    unix = self._time_str_to_unix(time_str, parsed["timestamp"])
                    if unix is not None:
                        slot_times.append(unix)
                    parsed["slots"].append({"name": name, "genre": genre, "duration": "60"})
                    continue
                # ── Names-only slot: any non-empty line inside LINEUP ─────
                parsed["names_only"] = True
                parsed["slots"].append({"name": line, "genre": "", "duration": "60"})
                continue

            # ── Genre line: "Genre1 // Genre2" ───────────────────────────
            if '//' in line:
                parsed["genres"] = [g.strip() for g in line.split("//") if g.strip()]
                continue

            # ── Title: first unrecognised line before LINEUP ──────────────
            if not parsed["title"]:
                self._split_title_vol(line, parsed)

        self._compute_slot_durations(parsed["slots"], slot_times)
        return parsed if (parsed["title"] or parsed["slots"]) else None

    # ── Helpers ───────────────────────────────────────────────────────────

    @staticmethod
    def _split_title_vol(candidate: str, parsed: dict):
        """Split 'Event Title VOL.3' into separate title and vol fields.

        Matches the exact format produced by ``EventSnapshot.full_title``:
        ``"{title} VOL.{vol}"`` when vol is a digit string.
        Writes directly into *parsed* in-place.
        """
        m = re.search(r'\s+VOL\.(\d+)\s*$', candidate, re.IGNORECASE)
        if m:
            parsed["vol"] = m.group(1)
            parsed["title"] = candidate[: m.start()].strip()
        else:
            parsed["title"] = candidate

    @staticmethod
    def _extract_name_genre(rest: str) -> tuple[str, str]:
        """Split the right-hand side of a slot line into (name, genre).

        Handles:
          ``Name (Genre)``  – parens
          ``Name [Genre]``  – square brackets
          ``Name - Genre``  – trailing dash / en-dash separator
          ``Name``          – no genre
        """
        name = rest.strip()
        genre = ""

        # (Genre) or [Genre] at end
        m = re.search(r'\s*[\(\[]([^\)\]]+)[\)\]]\s*$', name)
        if m:
            genre = m.group(1).strip()
            name = name[: m.start()].strip()
            return name, genre

        # " - Genre" or " – Genre" trailing suffix
        m = re.search(r'\s+[-–]\s+(.+)$', name)
        if m:
            possible_name = name[: m.start()].strip()
            if possible_name:          # only split if name part is non-empty
                genre = m.group(1).strip()
                name = possible_name

        return name, genre

    @staticmethod
    def _time_str_to_unix(time_str: str, timestamp_ctx: str) -> int | None:
        """Convert 'HH:MM' to unix seconds using the event date for context."""
        try:
            h, m = time_str.split(":")
            if timestamp_ctx:
                date_part = timestamp_ctx.split(" ")[0]
                dt = datetime.datetime.strptime(f"{date_part} {time_str}", "%Y-%m-%d %H:%M")
            else:
                today = datetime.date.today()
                dt = datetime.datetime(today.year, today.month, today.day, int(h), int(m))
            return int(dt.timestamp())
        except (ValueError, IndexError):
            return None

    @staticmethod
    def _compute_slot_durations(slots: list, slot_times: list[int]):
        """Fill in duration for each slot from consecutive start-time deltas."""
        if not slot_times or len(slot_times) != len(slots):
            return

        # Handle midnight wrap-around for plain-text times
        for i in range(1, len(slot_times)):
            if slot_times[i] <= slot_times[i - 1]:
                slot_times[i] += 86400  # +24h

        for i in range(len(slot_times)):
            if i + 1 < len(slot_times):
                diff = (slot_times[i + 1] - slot_times[i]) // 60
            else:
                diff = 0
            if 0 < diff <= 480:
                slots[i]["duration"] = str(diff)

    # ── Apply parsed data to editor ───────────────────────────────────────

    def _apply_parsed_event(self, parsed: dict):
        """Load parsed event data into the current editor state."""
        if parsed.get("title"):
            self.event_title_var.set(parsed["title"])
        if parsed.get("vol"):
            self.event_vol_var.set(parsed["vol"])
        if parsed.get("timestamp"):
            self.event_timestamp.set(parsed["timestamp"])

        if parsed.get("genres"):
            self.active_genres = parsed["genres"][:]
            for g in parsed["genres"]:
                if g.lower() not in [sg.lower() for sg in self.saved_genres]:
                    self.saved_genres.append(g)
            self._save_library()
            self.refresh_genre_tags()

        self.names_only.set(parsed.get("names_only", False))

        # Clear existing slots and rebuild
        for slot in self.slots:
            slot.destroy()
        self.slots.clear()

        for slot_data in parsed.get("slots", []):
            self.add_slot(
                slot_data.get("name", ""),
                slot_data.get("genre", ""),
                int(slot_data.get("duration", 60)),
            )

        # Save new DJs to roster (preserve existing entries that already have links)
        existing_names = {d.get("name", "").strip().lower() for d in self.saved_djs}
        added = False
        for slot_data in parsed.get("slots", []):
            name = slot_data.get("name", "").strip()
            # Skip open-decks placeholders like "Slot 1: [Available]"
            if not name or re.match(r'Slot\s+\d+', name, re.IGNORECASE):
                continue
            if name.lower() not in existing_names:
                self.saved_djs.append({"name": name, "stream": "", "exact_link": False})
                existing_names.add(name.lower())
                added = True
        if added:
            self._save_library()
            self._schedule_roster_refresh()
            self._refresh_slot_combos()

        if dpg.does_item_exist("left_tabs"):
            dpg.set_value("left_tabs", "Event")
        self.update_output()
